#小一机器人名称
xyrobot_name: '小一'
#机器人对主人的称呼
master_name: '陛下'
#时区
timezone: HKT
#机器人所在地
location: '北京'

# led灯配置
# led的正极针脚为5
# 该库使用Broadcom（BCM）引脚编号作为GPIO引脚，而不是物理（BOARD）编号。 
# 与RPi.GPIO库不同，这是不可配置的。
led_foot:5
# led灯的亮度，取值范围1-100,默认为10,越大越费电
led_brightness: 10
# led灯的图案样式，默认为googlehome，另外一个为echo，如果使用googlehome
# 则不需要进行配置
led_pattern: ''



#############################recording-config####################
snowboy_token: '6c4e7af384ec9fedbb42c82fefe73559dfabfa0c'
recording_timeout: 5 # 录制的语音最大长度（秒）

# 语音合成服务配置
# 可选值：
# han-tts       - HanTTS
# baidu-tts     - 百度语音合成（推荐）
# xunfei-tts    - 讯飞语音合成
# ali-tts       - 阿里语音合成（推荐）
# tencent-tts   - 腾讯云语音合成（推荐）
tts_engine: baidu-tts

# 语音识别服务配置
# 可选值：
# baidu-asr     - 百度在线语音识别
# xunfei-asr    - 讯飞语音识别
# ali-asr       - 阿里语音识别
# tencent-asr   - 腾讯云语音识别（推荐）
asr_engine: baidu-asr

# 百度语音服务
# http://yuyin.baidu.com/
baidu_yuyin:
    appid: '17127791'  # 建议使用自己的百度语音账户 APPID
    api_key: 'UY5hD5DgwnPB9DPPVVkjGenN'
    secret_key: 'wxhyyGEpTtajKLDOuTUUBAUopTzqEkSp'
    dev_pid: 1936   # 1936: 普通话远场，1536：普通话(支持简单的英文识别)，80001：ASR极速版（请使用自己的百度语音账户再使用）
    per: 4  # 发音人选择 0：女生；1：男生；3：度逍遥；4：度丫丫
    lan: 'zh'

# NLU 引擎
# 可选值：
# unit      - 百度 UNIT
nlu_engine: unit

# 聊天机器人
# 可选值：
# anyq      - AnyQ（推荐）
# tuling    - 图灵机器人
# emotibot  - 小影机器人
# robot: emotibot
robot: anyq
# AnyQ 机器人
anyq:
    host: 0.0.0.0
    port: 8999
    solr_port: 8900  # solr 的端口号
    # 置信度（confidence）需达到的阈值，
    # 达不到就认为不命中
    threshold: 0.6
    # 如果没有命中，使用其他兜底的机器人
    # 如果不想使用兜底，可以设为 null
    secondary: tuling

# 图灵机器人
# http://www.tuling123.com
# 在配置文件中添加图灵的集群配置，图灵免费版只能创建5个robot，所以这里需要配置5个，认证后每个100/天，共500/天，够用
# singleOrCluster: 1  # 0:代表single  1:代表集群 | default 1
tuling:
    singleOrCluster: 1  # 0:代表single  1:代表集群 | default 0
    tuling_key: 'de6210f00f3b41d1bfd8e2a1e783fd07'  # 建议使用自己的图灵机器人API Key
    cluster:
      - '69a5238782bb4bc1ad7910ebeb4e177b'
      - 'bf89eeffe73a4386acd9db6e948e1012'
      - '94ced0608f514874b35275b45c23ab51'
      - '0b6529e38d724b0fb0c122ab35e65255'

# 邮箱
# 如果使用网易邮箱，还需设置允许第三方客户端收发邮件
email:
    enable: true
    address: 'xiaoyikeji100@163.com'
    password: '123456xykj'  # 如果是网易邮箱，须填写应用授权密码而不是登录密码！
    smtp_server: 'smtp.163.com'
    smtp_port: '25'  # 这里填写非SSL协议端口号
    imap_server: 'imap.163.com'
    imap_port: '143'  # 这里填写非SSL协议端口号    
    read_email_title: true  # 当有邮件时，是否朗读邮件标题
    
## 本地音乐插件
LocalPlayer:
    path: "/Users/matianyi/.wukong/Music"  # 本地音乐存放路径
